; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
lib_deps = 
	D:\Data\Arduino\_inProduction\WFW_MQTT_IRreceive_4\src\Homie301_wfw.zip
	paulstoffregen/OneWire@^2.3.5
	milesburton/DallasTemperature@^3.9.1
	crankyoldgit/IRremoteESP8266@^2.7.13

lib_extra_dirs = C:\Program Files (x86)\Arduino\libraries
build_flags = -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY
lib_ignore = ESPAsyncTCP, Async WebServer


; Changes required to make the code work with the latest version of Homie (3.0.1) are based on hints 
; from https://github.com/giladger/ElectraWifi/tree/master and are marked in the code with "Changed by WFW on 20.03.2026".
; in .pio\libdeps\nodemcuv2\Homie\src\Homie\Boot\BootConfig.hpp and .pio\libdeps\nodemcuv2\Homie\src\Homie\Boot\BootConfig.cpp.

; Resolving nodemcuv2 dependencies...
; Platform espressif8266 @ 4.2.1 (required: espressif8266)
; ├── framework-arduinoespressif8266 @ 3.30102.0 (required: platformio/framework-arduinoespressif8266 @ ~3.30102.0)
; ├── tool-esptool @ 1.413.0 (required: platformio/tool-esptool @ <2)
; ├── tool-esptoolpy @ 1.30000.201119 (required: platformio/tool-esptoolpy @ ~1.30000.0)
; ├── tool-mklittlefs @ 1.203.210628 (required: platformio/tool-mklittlefs @ ~1.203.0)
; ├── tool-mkspiffs @ 1.200.0 (required: platformio/tool-mkspiffs @ ~1.200.0)
; └── toolchain-xtensa @ 2.100300.220621 (required: platformio/toolchain-xtensa @ ~2.100300.220621)

; Libraries
; ├── DallasTemperature @ 3.9.1 (required: milesburton/DallasTemperature @ ^3.9.1)
; │   └── OneWire @ 2.3.5 (required: paulstoffregen/OneWire @ ^2.3.5)
; ├── Homie @ 3.0.1 (required: file://D:\Data\Arduino\_inProduction\WFW_MQTT_IRreceive_4\src\Homie301_wfw.zip)
; │   ├── ArduinoJson @ 6.11.5 (required: ArduinoJson @ ~6.11.4)
; │   ├── AsyncMqttClient @ 0.8.2 (required: AsyncMqttClient @ ^0.8.0)
; │   │   └── ESPAsyncTCP @ 1.2.0 (required: ESPAsyncTCP @ 1.2.0)
; │   ├── Bounce2 @ 2.72.0 (required: Bounce2 @ ^2.1.0)
; │   └── ESP Async WebServer @ 3.0.6 (required: ESP Async WebServer)
; │   │   └── ESPAsyncTCP-esphome @ 2.0.0 (required: esphome/ESPAsyncTCP-esphome @ ^2.0.0)
; ├── IRremoteESP8266 @ 2.7.13 (required: crankyoldgit/IRremoteESP8266 @ ^2.7.13)